### ISSUE TITLE
Model options

### ISSUE THREAD

**Issue by HouQin** [twitter-research/graph-neural-pde#26]
Dear authors,

I hope this message finds you well. I am currently studying your implementation of the GRAND models and I have a question that I hope you could help me with.

In the code, I noticed that there are different 'block' options such as 'constant', 'attention', and 'hard_attention'. I am wondering if changing the 'block' corresponds to the different models in the GRAND paper. Specifically, does 'constant' correspond to GRAND-l, 'attention' to GRAND-nl, and 'hard_attention' to GRAND-nl-rw?

I would greatly appreciate your clarification on this matter. Thank you very much for your time and assistance.

Best regards

**Comment by JRowbottomGit** [comment]
Dear HouQin,

forgive me this has been a few years but I think it's slightly different to
your interpretation:

We set the ODE block and functions here:
graph-neural-pde/src/model_configurations.py at main ·
twitter-research/graph-neural-pde · GitHub
<https://github.com/twitter-research/graph-neural-pde/blob/main/src/model_configurations.py>

Both GRAND-L and GRAND-NL use the block:
  elif ode_str == 'attention':
    block = AttODEblock
(note block == 'constant' sets up a symmetrically normalised adjacency as
per GCN type model)

However GRAND-L uses the function:
  if ode_str == 'laplacian':
    f = LaplacianODEFunc
This is because it is sufficient to calculate the attention once at
initialisation of the block here:
https://github.com/twitter-research/graph-neural-pde/blob/af9047e0860e0ce6dc6333adcb4366769c795014/src/block_transformer_attention.py#L39
And then with the weights set one can run a simple attention weighted
Laplacian diffusion

and GRAND-NL uses the function:
  elif ode_str == 'transformer':
    f = ODEFuncTransformerAtt
Because the attention values need to be recalculated at each step of the
solver here:
https://github.com/twitter-research/graph-neural-pde/blob/af9047e0860e0ce6dc6333adcb4366769c795014/src/function_transformer_attention.py#L43

I hope this helps navigate the code better, good luck!

Best wishes
James

**Comment by HouQin** [comment]
I greatly appreciate your assistance! I have gained a more comprehensive understanding of both the paper and the code.
